// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cSharpBird.API;

#nullable disable

namespace cSharpBird.API.Migrations
{
    [DbContext(typeof(cSharpBirdContext))]
    [Migration("20240611191337_cSharpBirdNewDataModel_v1")]
    partial class cSharpBirdNewDataModel_v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CS_AS")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cSharpBird.API.Bird", b =>
                {
                    b.Property<Guid>("randomBirdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("checklistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("numSeen")
                        .HasColumnType("int");

                    b.Property<string>("speciesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("randomBirdId");

                    b.HasIndex("checklistId");

                    b.ToTable("Birds", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("cSharpBird.API.Checklist", b =>
                {
                    b.Property<Guid>("checklistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("checklistDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("locationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("checklistID");

                    b.ToTable("Checklists", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("cSharpBird.API.Salt", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Salts", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("cSharpBird.API.User", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("displayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hashedPW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("cSharpBird.API.Bird", b =>
                {
                    b.HasOne("cSharpBird.API.Checklist", null)
                        .WithMany("birds")
                        .HasForeignKey("checklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("cSharpBird.API.Checklist", b =>
                {
                    b.Navigation("birds");
                });
#pragma warning restore 612, 618
        }
    }
}
